services:
  mongo-booking:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_booking_data:/data/db

  mysql-user:
    image: mysql:latest
    ports:
      - 3309:3306
    volumes:
      - mysql_user_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-vehicle:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - mysql_vehicle_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-ride:
    image: mysql:latest
    ports:
      - 3308:3306
    volumes:
      - mysql_ride_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

volumes:
  mysql_user_data:
  mysql_vehicle_data:
  mysql_ride_data:
  mongodb_booking_data: