server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    reactor.netty: INFO
    org.springframework.security: TRACE
spring:
  application:
    name: api-gateway


  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/test
          filters:
            - SetPath=/api/user

        - id: vehicle-service
          uri: http://${VEHICLE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/vehicle/**

        - id: ride-service
          uri: http://${RIDE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/ride/**

        - id: booking-service
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/booking/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
