server:
  port: 8084

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: DEBUG
    reactor.netty: INFO
    org.springframework.security: TRACE


spring:
  application:
    name: api-gateway

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://${USER_SERVICE_BASEURL:localhost:8080}
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users(?<segment>/?.*), /api/user${segment}

        - id: vehicle-service
          uri: http://${VEHICLE_SERVICE_BASEURL:localhost:8081}
          predicates:
            - Path=/vehicles/**
          filters:
            - RewritePath=/vehicles(?<segment>/?.*), /api/vehicle${segment}

        - id: ride-service
          uri: http://${RIDE_SERVICE_BASEURL:localhost:8082}
          predicates:
            - Path=/rides/**
          filters:
            - RewritePath=/rides(?<segment>/?.*), /api/ride${segment}

        - id: booking-service
          uri: http://${BOOKING_SERVICE_BASEURL:localhost:8083}
          predicates:
            - Path=/bookings/**
          filters:
            - RewritePath=/bookings(?<segment>/?.*), /api/booking${segment}

