apiVersion: apps/v1
kind: Deployment
metadata:
    name: booking-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: booking-service
    template:
        metadata:
            labels:
                app: booking-service
        spec:
            containers:
                - name: booking-service
                  image: denyosh/booking-service
                  ports:
                      - containerPort: 8083
                  env:
                      - name: MONGODB_HOST
                        value: mongo-booking
                      - name: MONGODB_PORT
                        value: "27017"
