apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql-user
spec:
    replicas: 1
    selector:
        matchLabels:
            app: mysql-user
    template:
        metadata:
            labels:
                app: mysql-user
        spec:
            containers:
                - name: mysql-user
                  image: mysql:latest
                  ports:
                      - containerPort: 3306
                  env:
                      - name: MYSQL_ROOT_PASSWORD
                        value: "abc123"
                  volumeMounts:
                      - mountPath: /var/lib/mysql
                        name: mysql-user-data
            volumes:
                - name: mysql-user-data
                  persistentVolumeClaim:
                      claimName: mysql-user-data-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: mysql-user
spec:
    type: ClusterIP
    ports:
        - port: 3306
          targetPort: 3306
    selector:
        app: mysql-user
