apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: user-service
    template:
        metadata:
            labels:
                app: user-service
        spec:
            containers:
                - name: user-service
                  image: denyosh/user-service
                  ports:
                      - containerPort: 8080
                  env:
                      - name: MYSQL_DB_USERNAME
                        value: root
                      - name: MYSQL_DB_PASSWORD
                        value: abc123
                      - name: MYSQL_DB_HOST
                        value: mysql-user
                      - name: MYSQL_DB_PORT
                        value: "3306"
                      - name: VEHICLE_SERVICE_BASEURL
                        value: vehicle-service:8081
                      - name: RIDE_SERVICE_BASEURL
                        value: ride-service:8082
                      - name: BOOKING_SERVICE_BASEURL
                        value: booking-service:8083
