apiVersion: apps/v1
kind: Deployment
metadata:
    name: vehicle-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: vehicle-service
    template:
        metadata:
            labels:
                app: vehicle-service
        spec:
            containers:
                - name: vehicle-service
                  image: denyosh/vehicle-service
                  ports:
                      - containerPort: 8081
                  env:
                      - name: MYSQL_DB_USERNAME
                        value: root
                      - name: MYSQL_DB_PASSWORD
                        value: abc123
                      - name: MYSQL_DB_HOST
                        value: mysql-vehicle
                      - name: MYSQL_DB_PORT
                        value: "3306"
                      - name: USER_SERVICE_BASEURL
                        value: user-service:8080
                      - name: RIDE_SERVICE_BASEURL
                        value: ride-service:8082
                      - name: BOOKING_SERVICE_BASEURL
                        value: booking-service:8083
