apiVersion: v1
kind: Service
metadata:
    name: drivetogether-front
spec:
    type: NodePort
    ports:
        - port: 80
          targetPort: 80
          nodePort: 30001
    selector:
        app: drivetogether-front
